### PR TITLE
New output formats

### PR DESCRIPTION
**Pull request by klukonin**
rx_power is a tool for RTL-SDR receivers. It has a simple csv output format.

rtl_power_fftw is an modern tool for RTL-SDR receivers.
https://github.com/AD-Vega/rtl-power-fftw

All tests was done with UNBT UniFi AC MESH router.
Everything seems to be working.

### CODE REVIEW

**Comment by klukonin** [comment]
photo_2020-02-13_03-37-48

**Comment by simonwunderlich** [comment]
@klukonin Thank you very much for the contribution, this looks great! Two things:

 * It seems like you (implicitly) remove the copyright notice from the Makefile, can you please keep it?
 * It seems like your new two programs actually duplicate a lot of code from fft_eval_json. Would it make sens to integrate your new conversion functions into fft_eval_json and maybe rename it to fft_eval_convert which supports multiple outputs. I think we can consolidate quite a bit of code this way.

Thank you!

**Comment by klukonin** [comment]
Makefile was returned to it's previous state in the next commit. I can squash it if you want.

Well, currently I'm working on the next version with all computation in the main fft_eval module.

**Comment by klukonin** [comment]
But this also mean I should rework the sdl part.

And I think that formula has a little bit wrong format.
20 * log10(data) looks not obvious (I guess) to many people.

Also I've just read full mailing list thread about spectral scan and know something about this project.

**Comment by simonwunderlich** [comment]
Since you said you'd propose a new version, I'll close this pull request for now. Please reopen or create a new pull request once done. Thank you!

**Pull request closed without merging**
